/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package algorithm.test;

import java.util.Scanner;

public class App {
  public String getGreeting() {
    return "Hello World!";
    Scanner scanner = new Scanner(System.in);
    int[] nums = new int[10];
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
  }
}
